### ISSUE TITLE
xslt issue?

### ISSUE THREAD

**Issue by lrosenman** [neomutt/homebrew-neomutt#47] opened 2020-03-20 21:21 UTC
I got the following today:
installing /usr/local/Cellar/neomutt/20200313/share/locale/da/LC_MESSAGES/neomutt.mo
map mixmaster undefined at ./doc/gen-map-doc line 64, <XML> line 24.
map autocrypt account undefined at ./doc/gen-map-doc line 64, <XML> line 26.
xsltproc --nonet -o doc/ ./doc/chunk.xsl doc/manual.xml > /dev/null 2>&1
xsltproc --nonet -o doc/manual.html ./doc/html.xsl doc/manual.xml
installing /usr/local/Cellar/neomutt/20200313/share/locale/de/LC_MESSAGES/neomutt.mo
make: *** [doc/index.html] Error 5
make: *** Waiting for unfinished jobs....
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl"
compilation error: file ./doc/html.xsl line 3 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl
make: *** [doc/manual.html] Error 5

Ideas?

**Comment by flatcap** [comment] 2020-03-20 21:35
There are a couple of things here...

> map mixmaster undefined

These warnings come from code that isn't compiled-in.
You can ignore them, or `configure --full-doc`

> Attempt to load network entity

That's because you're missing the DocBook DTDs.
You'll need a package called something like, 'docbook-xsl' or 'docbook-dtds'

**Comment by lrosenman** [comment] 2020-03-20 21:45
Nope:
[I] ➜ brew install docbook-dtd
Error: No available formula with the name "docbook-dtd"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

~ took 3s
[I] ➜ brew install docbook-dtds
Error: No available formula with the name "docbook-dtds"
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

~ took 3s
[I] ➜

this used to work up till this update... :(

**Comment by lrosenman** [comment] 2020-03-20 21:46
[I] ➜ brew install docbook-xsl
Warning: docbook-xsl 1.79.2 is already installed and up-to-date
To reinstall 1.79.2, run `brew reinstall docbook-xsl`

~ took 2s

**Comment by flatcap** [comment] 2020-03-20 21:56
er...

What was your previous build?
(very little has changed with the docs, certainly nothing to do with how they're built)

**Comment by lrosenman** [comment] 2020-03-20 21:57
[I] ➜ brew info neomutt
zsh: correct 'neomutt' to '.neomutt' [nyae]? n
neomutt: stable 20200313 (bottled), HEAD
E-mail reader with support for Notmuch, NNTP and much more
https://neomutt.org/
/usr/local/Cellar/neomutt/20191207 (110 files, 7.4MB) *
  Built from source on 2019-12-09 at 20:47:01
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/neomutt.rb
==> Dependencies
Build: docbook-xsl ✔
Required: gettext ✔, gpgme ✔, libidn ✔, lmdb ✔, notmuch ✔, openssl@1.1 ✔, tokyo-cabinet ✔
==> Options
--HEAD
	Install HEAD version
==> Analytics
install: 523 (30 days), 1,223 (90 days), 6,557 (365 days)
install-on-request: 524 (30 days), 1,223 (90 days), 6,544 (365 days)
build-error: 0 (30 days)

~
[I] ➜

**Comment by flatcap** [comment] 2020-03-20 22:02
Since then, the docs have changed and a few source file locations, but...

> Attempt to load network entity

That's from `xsltproc` not being able to find the DTDs

**Comment by lrosenman** [comment] 2020-03-20 22:11
no clue.

I'm not at all sure what to do. :(

**Comment by lrosenman** [comment] 2020-03-20 22:11
what can I provide to help solve this?

**Comment by flatcap** [comment] 2020-03-20 22:27
sorry, not for homebrew

**Comment by lrosenman** [comment] 2020-03-20 22:54
anyone else have a clue?

**Comment by lrosenman** [comment] 2020-03-22 00:51
That's disappointing :( 

Hopefully, <someone> will find this and fix it.

**Comment by lrosenman** [comment] 2020-03-22 00:54
Has anyone successfully installed 2020-03-13 from homebrew? (I.E. is there something busted in my install?)

**Comment by lrosenman** [comment] 2020-03-22 01:22
Interestingly, I moved all my homebrew stuff away and reinstalled everything, and neomutt now installs from the pre-compiled binaries.

So, I'm not sure what's screwed up in the old install.  Closing this.

**Comment by jindraj** [comment] 2020-03-22 20:13
I am having issues installing neomutt from homebrew too. Just to add more information about this topic:

- This shouldn't affect people using bottled versions. Because when You install bottled versions, only deps are installed (also bottled if possible) and neomutt is just tar.gz archive untared.

- But when You're installing with `--HEAD` option Your neomutt is compiled. I noticed there was a new version (1.79.2) of docbook-xsl installed recently.

So uninstalling neomutt and installing it again (if You forget --HEAD option) You're good - You'll get bottled version.

As seen from info You provided
>Built from source on 2019-12-09 at 20:47:01
You built it from source
>Interestingly, I moved all my homebrew stuff away and reinstalled everything, and neomutt now installs from the pre-compiled binaries.
And after that You went the bottled way.

The issue persists. I think bisecting neomutt won't help since the behaviour changed with different version of docbook-xsl. I'll try to look into this later. I'm reopening the issue.

**Comment by jindraj** [comment] 2020-03-24 22:17
I just now noticed this is issue within neomutt/homebrew-neomutt. AFAIK this is unmaintained, but still I believe you're using homebrew-core based on your output. I  do also use homebrew core and the issue is there. I can't say if it's in this tap or not.

This is how the build fails
```
xsltproc --nonet -o doc/ ./doc/chunk.xsl doc/manual.xml > /dev/null 2>&1
xsltproc --nonet -o doc/manual.html ./doc/html.xsl doc/manual.xml
I/O error : Attempt to load network entity http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl
warning: failed to load external entity "http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl"
compilation error: file ./doc/html.xsl line 3 element import
xsl:import : unable to load http://docbook.sourceforge.net/release/xsl/current/xhtml/docbook.xsl
make: *** [doc/manual.html] Error 5
make: *** Waiting for unfinished jobs....
make: *** [doc/index.html] Error 5
```


1. removing `--nonet` option from xsltproc works for both xsltproc commands

2. changing `docbook.sourceforge.net` to `cdn.docbook.org` in [doc/chunk.xml](https://github.com/neomutt/neomutt/blob/master/doc/chunk.xsl#L3) and [doc/html.xsl](https://github.com/neomutt/neomutt/blob/master/doc/html.xsl#L3)

I tried to build it interactively: `brew install neomutt --HEAD -i`
```sh
export XML_CATALOG_FILES="/usr/local/etc/xml/catalog"
./configure --prefix=/usr/local/Cellar/neomutt/HEAD-a2b6a45 --enable-gpgme --with-gpgme=/usr/local/opt/gpgme --gss --lmdb --notmuch --sasl --tokyocabinet --with-ssl=/usr/local/opt/openssl@1.1 --with-ui=ncurses
gsed -i 's/docbook.sourceforge.net/cdn.docbook.org/' doc/chunk.xsl doc/html.xsl  #sry bsd sed doesn't have -i
make
make install
exit
```
and it worked. CC @flatcap what can we do about this?

**Comment by jindraj** [comment] 2020-03-25 10:53
My fork, current master with a addtional commit containing fix from above:
You can try 
```sh
brew edit neomutt
```
change `head` line to:  `head "https://github.com/jindraj/neomutt.git"` just temporarily.

and it works.
`brew install neomutt --HEAD`

**Comment by flatcap** [comment] 2020-03-25 11:35
> this is issue within neomutt/homebrew-neomutt. AFAIK this is unmaintained

Yes, me too: #39

> removing `--nonet` option from xsltproc works for both xsltproc commands

Maybe, but I don't want to require the use of the internet during a build.

**Comment by jindraj** [comment] 2020-03-25 13:28
Sorry my bad. the 1 and 2 are different options how to solve it. It's not a two step solution :)

so just changing the xsl:import domain should be enough. I'll try to test building it on linux later today.

**Comment by jindraj** [comment] 2020-03-26 08:55
Seems to be fixed by one or more of following commits to homebrew-core:

 - https://github.com/Homebrew/homebrew-core/commit/1aba4581ef39a7c3df3dd7f91e70400f61d5ddd4
 - https://github.com/Homebrew/homebrew-core/commit/a0ba32da750be5ede0d0d5da607bd6e7227defc3
 - https://github.com/Homebrew/homebrew-core/commit/8c92df0b3bfc24c2506e72ee57856f54ca741e46
 - https://github.com/Homebrew/homebrew-core/commit/16126c1022df2df6b7c4a64ff36139d49b662f8e

**Closed by jindraj** 2020-03-26 08:55 UTC
