### ISSUE TITLE
neomutt installing with no sidebars

### ISSUE THREAD

**Issue by twirrim** [neomutt/homebrew-neomutt#14] opened 2016-09-23 23:21 UTC
NeoMutt 20160916 (1.7.0)

configure options end up:
Configure options: '--disable-dependency-tracking' '--disable-warnings' '--prefix=/usr/local/Cellar/neomutt/20160916' '--with-ssl=/usr/local/opt/openssl' '--with-sasl' '--with-gss' '--enable-imap' '--enable-smtp' '--enable-pop' '--enable-hcache' '--with-tokyocabinet' '--disable-nls' '--disable-debug' 'CC=clang'

What's missing there is --enable-sidebar, for some reason, although the version of neomutt built does include the patches.

I tried to look at the underlying .rb file used, but I'm not familiar enough with homebrew to understand how to fix it.

My somewhat blind stab-in-the-dark guess is that it's the disparity between line 11:
https://github.com/neomutt/homebrew-neomutt/blob/master/Formula/neomutt.rb#L11 where the option is set as "with-sidebar-patch" but down in line 57:
https://github.com/neomutt/homebrew-neomutt/blob/master/Formula/neomutt.rb#L57 seems to be expecting "sidebar-patch" as the option?  If that is the problem, it looks like notmuch will have the same one.

**Comment by alexpearce** [comment] 2016-09-24 06:43
The options are passed to `configure` if the formula is built with the corresponding flags, for example:

```shell
$ brew install neomutt --with-sidebar-patch --with-notmuch-patch
```

**Comment by alexpearce** [comment] 2016-10-01 10:56
Closing as I think this has been addressed. Please leave a comment if this isn't the case.

**Closed by alexpearce** 2016-10-01 10:56 UTC

**Comment by ludovicchabant** [comment] 2016-10-08 20:26
I just started using Neomutt and it took me a little time to realize that the sidebar patch wasn't applied by default... I may be mistaken but aren't those patches the whole point of using Neomutt instead of vanilla Mutt? Is there a reason to not include those patches by default?

**Comment by alexpearce** [comment] 2016-10-09 08:46
I think the point is more that those patches are available, and that NeoMutt is very much more open to accepting additional patches. Still, I get your point (I always include the sidebar patch), so I've opened issue #16 to discuss.

**Comment by rlue** [comment] 2017-04-29 14:17
I hate to raise an issue from the grave here, but @telemachus points out in issue #16 that

> as of 1.7.0 mutt has merged the sidebar patch

yet I still need to specify `--with-sidebar-patch` when installing neomutt (v1.8.2) to get it enabled (otherwise, `set sidebar_visible` throws the following error:

    sidebar_visible: unknown variable

I can confirm that vanilla mutt indeed features the sidebar (had it working just before replacing mutt with neomutt), whereas neomutt somehow needs the patch applied to get it?

**Comment by flatcap** [comment] 2017-04-29 15:16
The sidebar code is in both upstream Mutt and NeoMutt, it's just not enabled by default.
The Homebrew option is a little misleading, it's not patching anything, it's just enabling code.

NeoMutt is planning to enable some features by default as long as they don't have any build dependencies.

**Comment by rlue** [comment] 2017-05-02 03:22
Ah, I was confused then because I didn't have to set any install flags to get the sidebar in vanilla mutt – its homebrew formula must include the sidebar option by default.

Thanks for the clarification.
